server:
  port: 8080

spring:
  application:
    name: millie-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/millie_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
